const chapter7MindMap = [
["Work","Scientific meaning","Force does work on an object when it produces displacement in the force direction."],
["Work","Formula","W = F × s for a constant force acting along displacement."],
["Work","SI unit","Joule (J); 1 J = 1 N m = 1 kg m² s⁻²."],
["Work","Zero work","F = 0, displacement = 0, or force perpendicular to displacement."],
["Work","Positive work","Force and displacement are in the same direction."],
["Work","Negative work","Force and displacement are in opposite directions."],
["Work","Force–displacement graph","Work equals the area under the graph between the positions."],
["Work","Name the agent and object","Always specify which force does work on which object."],
["Work–energy theorem","Core relation","Work done on an object equals the change in its energy."],
["Energy","Definition","Energy is the capacity to do work; SI unit is joule."],
["Energy","Forms","Mechanical, thermal, light, sound, electrical, nuclear and chemical energy."],
["Mechanical energy","Kinetic energy","Energy due to motion; K = ½mv²."],
["Mechanical energy","Potential energy","Energy stored through deformation or relative position in a system."],
["Mechanical energy","Gravitational potential energy","Near Earth's surface, U = mgh, taking a reference height."],
["Mechanical energy","Conservation","In the ideal gravity-only model, K + U remains constant."],
["Energy conversion","Free fall","Potential energy decreases as kinetic energy increases."],
["Energy conversion","Pendulum","At extremes, kinetic energy is zero; at the lowest point, kinetic energy is greatest."],
["Power","Definition","Rate at which work is done or energy is transferred."],
["Power","Formula and unit","P = W/t; 1 W = 1 J/s. The sidebar also gives 1 hp = 746 W."],
["Simple machines","Purpose","Change the magnitude or direction of applied force; do not create energy."],
["Simple machines","Effort and load","Effort is the applied force; load is the force to overcome."],
["Simple machines","Mechanical advantage","MA = load / effort."],
["Pulley","Fixed pulley","Changes direction of effort; ideal MA = 1."],
["Pulley","Movable pulley system","Can provide MA > 1; load is attached to the movable pulley."],
["Inclined plane","Trade-off","Longer, gentler ramp reduces effort force but increases distance."],
["Inclined plane","Mechanical advantage","Ignoring friction, MA = ramp length / vertical height = L/h."],
["Lever","Parts","Fulcrum, effort, load, effort arm and load arm."],
["Lever","Balance relation","Effort × effort arm = load × load arm."],
["Lever","Mechanical advantage","MA = effort arm / load arm for the ideal lever relation in the chapter."],
["Lever","Classes","Class I: fulcrum between; Class II: load between; Class III: effort between."],
["Machines","Energy conservation","Ignoring friction, input work equals useful work on the load; smaller effort means greater effort distance."],
["Applications","Watermill","Water PE → water KE → wheel rotation → grinding-stone motion."]
];
export default chapter7MindMap;