export default [
["What is the definition of linear motion according to the textbook?","Motion along a straight line."],
["Which two specifications are strictly required to describe the position of an object relative to a reference point?","Distance and direction."],
["When is an object considered to be in motion relative to a reference point?","When its position changes with time relative to the reference point."],
["Which statement correctly distinguishes total distance travelled from displacement?","Distance depends on total path length, while displacement is the net change in position."],
["Under what condition are total distance and displacement magnitude equal?","When the object moves along a straight line in one direction without turning back."],
["A ball rises 40 cm and returns to O. What are distance and displacement magnitude?","Distance = 80 cm; displacement magnitude = 0 cm."],
["What general property of displacement magnitude is always true?","It is less than or equal to total distance travelled."],
["How is average speed defined?","Total distance divided by the time interval."],
["Unequal distances in equal time intervals indicate what type of motion?","Non-uniform motion in a straight line."],
["Two postmen are 210 yojanas apart and walk toward each other at 9 and 5 yojanas/day. When do they meet?","15 days."],
["How is average velocity defined?","Displacement divided by the time interval."],
["Sarang swims 25 m to the other end and back in 50 s. What are average speed and average velocity?","Average speed = 1 m/s; average velocity = 0 m/s."],
["When is average velocity zero while average speed is non-zero?","When an object completes a closed journey and returns to its starting point."],
["What is the formula for average acceleration?","a = (v - u) / t."],
["If a vehicle is slowing down, how is average acceleration directed relative to velocity?","Opposite to the direction of velocity."],
["A bus accelerates from 36 km/h (10 m/s) to 54 km/h (15 m/s) in 10 s. What is its average acceleration?","0.5 m/s²."],
["A bus travelling at 54 km/h (15 m/s) stops in 5 s. What is its average acceleration?","-3 m/s²."],
["What is the constant vertical acceleration of a freely falling object near Earth's surface?","9.8 m/s² downward."],
["What does a vehicle's speedometer reading represent at an instant?","Nearly the magnitude of velocity at that instant."],
["What does a horizontal position-time graph represent?","An object at rest."],
["What physical quantity is given by the slope of a position-time graph?","Velocity."],
["What does a curved position-time graph indicate?","Accelerated motion with changing velocity."],
["What physical quantity is given by the slope of a velocity-time graph?","Acceleration."],
["How is displacement calculated from a velocity-time graph?","By calculating the area under the velocity-time curve."],
["Which kinematic equation relates u, v, a and s without requiring time?","v² = u² + 2as."],
["After one full circular revolution of radius R, what are distance and net displacement?","Distance = 2πR; displacement = 0."],
["For uniform circular motion with radius R and period T, what is speed?","v = 2πR/T."],
["Why is uniform circular motion accelerated even when speed is constant?","Because the direction of velocity changes continuously."]
];