export default [
["Force","Effects of force","Can move an object from rest, change speed or direction, and change shape."],
["Force","Vector-like attributes","Magnitude, direction and unit must be specified."],
["Force","SI unit","newton, symbol N."],
["Force","Measuring force","A spring balance measures the magnitude of a force."],
["Forces","Balanced forces","Equal magnitude and opposite direction; net force is zero."],
["Forces","Unbalanced forces","Non-zero net force acts on the object."],
["Forces","Same direction","Net-force magnitudes add."],
["Forces","Opposite directions","Net-force magnitude is the difference; direction follows the larger force."],
["Friction","Direction","For the box examples, friction acts opposite the motion."],
["Friction","Surface dependence","Activity 6.1 compares surfaces and shows smaller friction lets velocity decrease more slowly."],
["Friction","Spring-balance comparison","Activity 6.2 uses scale readings to compare friction on different surfaces."],
["Friction","Walking","Ground friction can act forward and help a person move."],
["Newton 1","First law","Zero net force means rest remains rest or constant velocity continues."],
["Newton 1","Inertia","Tendency to resist change in state of rest or uniform motion."],
["Newton 1","Rest graph","x-t horizontal; v-t at zero."],
["Newton 1","Constant-velocity graph","x-t straight line; v-t horizontal."],
["Newton 2","Core relationship","a = F/m and F = ma."],
["Newton 2","Force relation","For fixed mass, acceleration increases with net force."],
["Newton 2","Mass relation","For fixed force, acceleration decreases as mass increases."],
["Newton 2","Unit of force","1 N = 1 kg m/s²."],
["Gravity","Weight","F = mg; g = 9.8 m/s² near Earth's surface; 10 m/s² for quick estimates."],
["Applications","Stopping time","Longer stopping time lowers acceleration magnitude and force for the same velocity change."],
["Newton 3","Third law","Equal and opposite forces act simultaneously on two different objects."],
["Newton 3","Examples","Walking, rowing, rocket propulsion, magnetic/electrostatic/gravitational interactions."],
["Newton 3","Equal force ≠ equal acceleration","Different masses can have different accelerations under equal force magnitudes."],
["Systems","Two-box system","Internal tension can be ignored when analysing the whole system."],
["Systems","System acceleration","a = F/(m1 + m2) for the frictionless two-box setup."],
["Graphs","v-t slope","Slope gives acceleration; combine with mass to obtain force."],
["History","Galileo and Newton","Galileo's thought experiments helped challenge the old idea that continuous force is needed; Newton formulated the three laws in 1687."]
];