export default [
["Motion","Motion in a straight line","Linear motion is the simplest kind of motion."],
["Motion","Describing position","Use a reference point/origin plus distance and direction."],
["Motion","State of an object","Motion means position changes with time; rest means position does not change."],
["Motion","Distance travelled","Total length of the actual path."],
["Motion","Displacement","Net change in position; its magnitude is less than or equal to distance."],
["Motion","Scalar vs vector","Distance and speed are scalar; displacement and velocity are vector."],
["Motion","Average speed","Total distance divided by time interval."],
["Motion","Average velocity","Displacement divided by time interval."],
["Motion","Average acceleration","Change in velocity divided by time interval."],
["Motion","Gravity","Freely falling objects near Earth have 9.8 m/s² downward acceleration."],
["Motion","Uniform motion","Equal distances in equal time intervals."],
["Motion","Non-uniform motion","Unequal distances in equal time intervals."],
["Graphs","Position-time graph","Slope gives velocity; horizontal means rest; curved means changing velocity."],
["Graphs","Velocity-time graph","Slope gives acceleration; area under the graph gives displacement."],
["Kinematics","Three core equations","v = u + at; s = ut + 1/2 at²; v² = u² + 2as."],
["Kinematics","Other useful forms","s = 1/2(u + v)t and s = vt - 1/2at²."],
["Kinematics","Condition","Standard kinematic equations require constant acceleration."],
["Circular motion","Uniform circular motion","Constant speed on a circular path, but changing velocity direction."],
["Circular motion","One revolution","Distance = 2πr; displacement = 0; average velocity = 0."],
["Circular motion","Speed","v = 2πr/T."],
["Applications","Unit conversion","km/h to m/s: multiply by 5/18."],
["Applications","Two-postmen problem","210 yojanas apart; combined closing speed 14 yojanas/day; meet in 15 days."],
["Applications","Sarang's pool example","25 m out and back in 50 s gives average speed 1 m/s and average velocity 0."],
["History","Indian mathematics","The chapter references Aryabhatiya and Ganitakaumudi."]
];