const chapter6Lessons = [
  {
    key:"force-concept", title:"What is force?", section:"6.1 The Concept of Force", pages:"94–95",
    hook:"Force is the cause we use to explain changes in motion and, in some cases, changes in shape.",
    textbook:"The chapter introduces force through familiar effects: starting a ball from rest, changing a moving ball's direction, and squeezing a lemon.",
    teacher:"Think of force as an interaction that can push or pull on an object. In this chapter, the important question is what the net force does to motion.",
    example:"Kicking a stationary ball gives it a motion; striking a moving cricket ball can change its direction; squeezing a lemon changes its shape.",
    interaction:{type:"choice",prompt:"Which is an effect of an applied force described in the chapter?",options:["Changing an object's motion","Only changing its colour","Only changing its temperature","No physical effect"],answer:0,explain:"The chapter states that force can move an object, change speed or direction, and change shape."},
    mistake:"Do not assume every individual force determines motion by itself. Later in the chapter, motion is tied to the net force.",
    checkpoint:{prompt:"What can a force change?","answer":"Motion and, in some situations, shape."},
    textbookActivity:"Revisit the ball, cricket-bat and lemon examples and identify the effect of the force in each case.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.1 The Concept of Force, pp. 94–95"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"force-vector", title:"Force has magnitude and direction", section:"6.1 The Concept of Force", pages:"95",
    hook:"A force is not fully described by saying only how strong it is; its direction matters too.",
    textbook:"The chapter explicitly says force requires direction along with magnitude and unit, just like position, displacement, velocity and acceleration.",
    teacher:"Two equal-sized pushes in opposite directions do not have the same effect as two pushes in the same direction. Direction is part of the information.",
    example:"Friction acts opposite the direction of motion, gravity acts toward Earth, and buoyant force acts upward.",
    interaction:{type:"choice",prompt:"Which three attributes are used to specify a force?",options:["Magnitude, direction and unit","Mass, colour and volume","Time, distance and density","Speed, energy and temperature"],answer:0,explain:"The chapter says force needs magnitude, direction and unit."},
    mistake:"Never write only a number for a force when direction is important. State the direction too.",
    checkpoint:{prompt:"What must be specified along with the magnitude of force?","answer":"Direction and unit."},
    textbookActivity:"List three forces from the chapter and write their directions.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.1, pp. 95"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"force-unit", title:"The newton: unit of force", section:"6.1 The Concept of Force", pages:"95",
    hook:"The SI unit of force is the newton, written as N.",
    textbook:"The SI unit of force is newton (small n in the word) and its symbol is N. The magnitude expresses the strength of the force.",
    teacher:"Keep the spelling and symbol straight: newton is the unit name; N is the symbol.",
    example:"A force of 12 N means a force whose magnitude is twelve newtons.",
    interaction:{type:"choice",prompt:"Which is the SI unit symbol for force?",options:["N","kg","J","m/s"],answer:0,explain:"Force is measured in newtons and the symbol is N."},
    mistake:"Do not write the unit symbol as lowercase n. The chapter specifically distinguishes newton from N.",
    checkpoint:{prompt:"What is the SI unit and symbol of force?","answer":"newton (N)."},
    textbookActivity:"Write five example forces with the unit N and an indicated direction.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.1, pp. 95"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"spring-balance", title:"Measuring force with a spring balance", section:"6.1.1 Measuring the magnitude of a force", pages:"95",
    hook:"A spring balance can measure the magnitude of a force, not only weight.",
    textbook:"The chapter explains that pulling the free end of a spring balance measures the force with which you pull the spring. It can also be used to measure weight.",
    teacher:"The scale reading is a force reading. In the friction activity, the spring balance becomes a practical way to compare frictional forces.",
    example:"A block is pulled horizontally with a spring balance. The reading when it just starts moving gives an approximate measure of the friction acting.",
    interaction:{type:"choice",prompt:"What does a spring balance measure in this chapter?",options:["Magnitude of force","Only mass","Only distance","Only time"],answer:0,explain:"The chapter says the spring balance measures the magnitude of a force in general."},
    mistake:"Do not confuse a spring-balance force reading with a mass reading.",
    checkpoint:{prompt:"What quantity does the spring balance reading represent?","answer":"The magnitude of a force."},
    textbookActivity:"Use the chapter's Activity 6.2 as the reference for comparing friction on different surfaces.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.1.1, p. 95; Activity 6.2, p. 99"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"balanced-forces", title:"Balanced forces", section:"6.2 Balanced and Unbalanced Forces", pages:"95–96",
    hook:"Equal forces in opposite directions can leave the net force at zero.",
    textbook:"Forces that are equal in magnitude and opposite in direction are called balanced forces.",
    teacher:"Balanced does not mean that no forces exist. It means their combined effect on the object's translational motion is zero.",
    example:"In tug of war, if both teams pull equally in opposite directions, the rope does not move.",
    interaction:{type:"choice",prompt:"Two opposite forces of equal magnitude act on an object. What is the net force?",options:["Zero","Their sum in one direction","The larger force","It cannot be found"],answer:0,explain:"Equal opposite forces cancel in the net-force calculation."},
    mistake:"Do not say 'no forces are acting' when the correct statement is 'the net force is zero'.",
    checkpoint:{prompt:"What is the net force for equal opposite forces?","answer":"Zero."},
    textbookActivity:"Use the tug-of-war example to identify individual forces and the net force.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.2, pp. 95–96"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"opposite-net", title:"Net force: opposite directions", section:"6.2 Balanced and Unbalanced Forces", pages:"96",
    hook:"When opposite forces have different magnitudes, the net force points toward the larger one.",
    textbook:"For two opposite unequal forces, the net-force magnitude is the difference between their magnitudes, with direction along the larger force.",
    teacher:"Choose one positive direction, then subtract algebraically. The sign carries the direction.",
    example:"For 10 N right and 6 N left, net force = 10 − 6 = 4 N right.",
    interaction:{type:"numeric",prompt:"A 12 N force acts right and a 7 N force acts left. Find the net force magnitude.",answer:"5 N to the right",explain:"Opposite forces are subtracted: 12 − 7 = 5 N, toward the larger 12 N force."},
    mistake:"Do not add opposite forces as though they point in the same direction.",
    checkpoint:{prompt:"How do you find the net force for two opposite unequal forces?","answer":"Subtract magnitudes and keep the direction of the larger force."},
    textbookActivity:"Rework Example 6.1 for all three force arrangements.",
    sources:["NCERT Class 9 Science, Chapter 6, Example 6.1, p. 96"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"same-direction-net", title:"Net force: same direction", section:"6.2 Balanced and Unbalanced Forces", pages:"96",
    hook:"Forces acting in the same direction reinforce each other.",
    textbook:"When two people apply forces in the same direction, the net-force magnitude is the sum of the individual magnitudes and the direction is the same as theirs.",
    teacher:"Same direction means add. Opposite direction means subtract.",
    example:"Two people push a stalled car in the same direction with 50 N and 30 N. The net force is 80 N in that direction.",
    interaction:{type:"numeric",prompt:"Two forces of 9 N and 11 N act in the same direction. Find the net force.",answer:"20 N",explain:"Same-direction forces add: 9 + 11 = 20 N."},
    mistake:"Do not subtract forces just because there are two of them. Their directions decide the operation.",
    checkpoint:{prompt:"What do you do with same-direction forces?","answer":"Add their magnitudes and keep the common direction."},
    textbookActivity:"Compare the same-direction and opposite-direction cases from Fig. 6.4–6.5.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.2, p. 96"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"unbalanced-forces", title:"Unbalanced forces and net force", section:"6.2 Balanced and Unbalanced Forces", pages:"96",
    hook:"A non-zero net force is the quantity that matters for changes in motion.",
    textbook:"If the forces are not balanced, a non-zero net force acts on the object. Its direction is determined by the force combination.",
    teacher:"Stop tracking every force separately once you know the net force for a simple one-dimensional problem. The net result is what links to acceleration.",
    example:"If 10 N right and 6 N left act, the object has a 4 N net force right.",
    interaction:{type:"choice",prompt:"Which condition gives a non-zero net force?",options:["Unequal opposite forces","Equal opposite forces","No forces","Any two forces regardless of direction"],answer:0,explain:"Unequal opposite forces leave a non-zero difference."},
    mistake:"A moving object can still have zero net force; motion itself does not prove a force is acting.",
    checkpoint:{prompt:"What does a non-zero net force mean?","answer":"The forces are not balanced and the object has a net force."},
    textbookActivity:"Take several two-force examples and calculate the net force before discussing motion.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.2, p. 96"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"force-diagram", title:"Forces acting on a pushed box", section:"6.3 The Force of Friction", pages:"97",
    hook:"A real object can have several forces at once: push, friction, weight and normal force.",
    textbook:"The chapter's box diagram shows applied force, friction, gravitational force and the normal force from the surface.",
    teacher:"Separate vertical and horizontal effects. On a horizontal surface, weight acts down and normal force acts up; the horizontal motion is decided by the horizontal net force.",
    example:"A box being pushed right has applied force right and friction opposite the motion, while weight and normal force act vertically.",
    interaction:{type:"choice",prompt:"Which force acts upward on a box resting on a horizontal surface?",options:["Normal force","Weight","Friction only","Applied force"],answer:0,explain:"The chapter identifies the normal force as the upward force perpendicular to the surface."},
    mistake:"Do not automatically treat every force as acting along the direction of motion.",
    checkpoint:{prompt:"Name the four forces shown for the pushed box.","answer":"Applied force, friction, gravitational force and normal force."},
    textbookActivity:"Sketch the force directions for a box pushed across a horizontal floor.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.3, pp. 97"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"friction", title:"Friction resists relative motion", section:"6.3 The Force of Friction: Often Overlooked but Always Present", pages:"97–99",
    hook:"The force that often stops everyday motion is friction.",
    textbook:"Friction acts between surfaces in contact and, for the pushed-box examples, acts opposite the direction of motion or attempted motion.",
    teacher:"Friction is not automatically 'bad'. In this chapter it can oppose sliding motion, but later it also helps us walk and run.",
    example:"Stop pushing a ball and friction gradually reduces its velocity until it stops.",
    interaction:{type:"choice",prompt:"For a sliding box, friction generally acts in which direction?",options:["Opposite the direction of motion","Same direction as motion","Always vertically upward","Always vertically downward"],answer:0,explain:"The chapter states that friction acts opposite to the direction of motion in the examples discussed."},
    mistake:"Do not claim friction is always opposite every possible movement without considering the interaction. The walking example later shows friction can propel a person forward.",
    checkpoint:{prompt:"What is the chapter's basic direction rule for friction on the sliding box?","answer":"Opposite the direction of motion."},
    textbookActivity:"Compare the box, bicycle and ball examples in the friction section.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.3, pp. 97–99"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"friction-surface", title:"Friction depends on the surfaces", section:"6.3 The Force of Friction", pages:"98–99",
    hook:"The same initial push can produce different travel distances on different surfaces.",
    textbook:"Activity 6.1 compares wood, cement, laminated surfaces and polished marble/tile. Smaller friction makes velocity decrease more slowly and the object travel farther.",
    teacher:"The experiment is qualitative: keep the rubber-band pull setup comparable and compare how the surface changes the motion.",
    example:"The coin stack travels farther on a smoother surface because its velocity decreases more slowly there.",
    interaction:{type:"choice",prompt:"According to Activity 6.1, on a surface with smaller friction the coins generally travel:",options:["Farther before stopping","A shorter distance","Exactly zero distance","The same distance in every case"],answer:0,explain:"The chapter concludes that smaller friction makes the velocity decrease more slowly and the stack travel a larger distance."},
    mistake:"Do not confuse 'larger friction' with 'larger distance travelled' in this experiment; the relationship is opposite.",
    checkpoint:{prompt:"What happens when the frictional force is smaller?","answer":"Velocity decreases more slowly and the object travels farther before stopping."},
    textbookActivity:"Carry out the chapter's Activity 6.1 with the listed surfaces if materials are available.",
    sources:["NCERT Class 9 Science, Chapter 6, Activity 6.1, p. 98"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"friction-measure", title:"Measuring friction with a spring balance", section:"6.3 The Force of Friction", pages:"99",
    hook:"A spring-balance reading can be used to compare frictional forces on different surfaces.",
    textbook:"Activity 6.2 asks you to pull a block gradually and note the spring-balance reading when it just starts moving, then repeat the test on several surfaces.",
    teacher:"In the chapter's stated interpretation, a smaller reading indicates smaller friction and a larger reading indicates larger friction.",
    example:"If one surface gives a smaller spring-balance reading than another, the chapter treats it as having a smaller frictional force in that comparison.",
    interaction:{type:"choice",prompt:"What does a larger spring-balance reading indicate in Activity 6.2?",options:["A larger frictional force","A smaller frictional force","Zero friction","A larger mass automatically"],answer:0,explain:"The chapter says a larger reading indicates a larger force of friction."},
    mistake:"Do not turn this qualitative activity into an invented friction coefficient calculation; the chapter does not give such a formula here.",
    checkpoint:{prompt:"How does the spring-balance reading compare friction?","answer":"Smaller reading → smaller friction; larger reading → larger friction."},
    textbookActivity:"Compare four surfaces as instructed in Activity 6.2.",
    sources:["NCERT Class 9 Science, Chapter 6, Activity 6.2, p. 99"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"zero-friction", title:"The zero-friction thought experiment", section:"6.3 The Force of Friction", pages:"99–100",
    hook:"Remove friction in your imagination and a familiar idea about motion changes completely.",
    textbook:"The chapter asks what would happen if an object and a horizontal floor had zero friction: would velocity decrease, or would the object continue moving?",
    teacher:"The thought experiment prepares the way for Newton's first law: without a net force, motion does not need a continuous push to continue.",
    example:"A moving object on a perfectly frictionless horizontal surface would not slow because of friction.",
    interaction:{type:"choice",prompt:"In the chapter's ideal zero-friction horizontal-floor thought experiment, what removes the usual slowing effect?",options:["Friction is zero","Mass becomes zero","Gravity becomes zero","Velocity becomes zero"],answer:0,explain:"The thought experiment specifically removes friction."},
    mistake:"Do not interpret the thought experiment as saying every real surface is frictionless. It is an idealisation.",
    checkpoint:{prompt:"Why is the zero-friction thought experiment important?","answer":"It shows that continuous force is not required to maintain uniform motion when net force is zero."},
    textbookActivity:"Write what you predict before reading Newton's first law, then compare your answer with the next section.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.3–6.4, pp. 99–100"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"newton-first-law", title:"Newton's First Law", section:"6.4 Newton’s First Law of Motion", pages:"100–101",
    hook:"No net force means no change in velocity.",
    textbook:"An object at rest remains at rest and an object in motion continues with constant velocity unless a net force acts on it.",
    teacher:"The law says what happens when the net force is zero: acceleration is zero, so velocity does not change.",
    example:"A moving box experiences equal forward applied force and backward friction. The net force is zero, so it keeps moving with constant velocity.",
    interaction:{type:"choice",prompt:"What does Newton's first law predict when net force is zero?",options:["Velocity remains unchanged","Velocity must increase","Velocity must decrease","The object must stop"],answer:0,explain:"The law says rest remains rest and motion continues with constant velocity."},
    mistake:"Do not replace 'zero net force' with 'zero velocity'. A moving object can have zero net force.",
    checkpoint:{prompt:"State Newton's first law in one sentence.","answer":"Rest stays rest and uniform motion continues unless a net force acts."},
    textbookActivity:"Apply the law to the moving-box example and explain why it does not stop.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.4, p. 100"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"inertia", title:"Inertia: resistance to change", section:"6.4 Newton’s First Law of Motion", pages:"100",
    hook:"Objects resist changes to their current state of rest or uniform motion.",
    textbook:"The chapter says Isaac Newton used the word inertia for the tendency of objects to resist change in their state of rest or uniform motion.",
    teacher:"Inertia is not an extra force. It describes the object's tendency to keep its current velocity unless a net force changes it.",
    example:"A moving object keeps moving at constant velocity in the ideal no-net-force case.",
    interaction:{type:"choice",prompt:"In the chapter, inertia is the tendency to:",options:["Resist change in state of rest or uniform motion","Increase force automatically","Reduce mass","Create friction"],answer:0,explain:"That is the chapter's definition in the first-law discussion."},
    mistake:"Do not draw inertia as a separate force in a force diagram.",
    checkpoint:{prompt:"What does inertia describe?","answer":"The tendency to resist a change in rest or uniform motion."},
    textbookActivity:"Give one everyday example that illustrates resistance to a change in motion.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.4, p. 100"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"first-law-graphs-rest", title:"First-law graphs: object at rest", section:"6.4 Newton’s First Law of Motion", pages:"101",
    hook:"Zero net force can mean an object simply stays where it is.",
    textbook:"For an object at rest with no net force, the position-time graph is horizontal and the velocity-time graph is at zero.",
    teacher:"Position not changing means a horizontal x-t graph. Zero velocity means the v-t graph sits on the time axis.",
    example:"An object at fixed position x0 has x constant, so its position-time graph is a horizontal line.",
    interaction:{type:"choice",prompt:"What is the position-time graph of an object at rest?",options:["A horizontal line","A rising straight line","A curved line","A vertical line"],answer:0,explain:"The object's position does not change with time."},
    mistake:"A horizontal position-time graph means rest, not 'zero distance on every graph'.",
    checkpoint:{prompt:"What do the x-t and v-t graphs look like for rest?","answer":"Horizontal x-t line and v = 0 horizontal v-t line."},
    textbookActivity:"Sketch both graphs for a stationary object using the textbook's Fig. 6.15 as the reference.",
    sources:["NCERT Class 9 Science, Chapter 6, Example 6.3, p. 101"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"first-law-graphs-motion", title:"First-law graphs: constant velocity", section:"6.4 Newton’s First Law of Motion", pages:"101",
    hook:"Uniform straight-line motion has a signature on both position-time and velocity-time graphs.",
    textbook:"For constant velocity and zero net force, the position-time graph is a straight line and the velocity-time graph is horizontal.",
    teacher:"The x-t line has constant slope, and the v-t graph stays at one velocity value.",
    example:"A body moving at a constant 4 m/s has a straight-line position-time graph and a horizontal v-t line at 4 m/s.",
    interaction:{type:"choice",prompt:"For constant non-zero velocity with no net force, the velocity-time graph is:",options:["Horizontal above or below zero","Always sloped upward","Always curved","A vertical line"],answer:0,explain:"Constant velocity means the v-t graph is parallel to the time axis."},
    mistake:"Do not confuse a horizontal v-t graph with a horizontal x-t graph. Only the latter represents rest.",
    checkpoint:{prompt:"What are the graph signatures of constant velocity?","answer":"Straight-line x-t graph and horizontal v-t graph."},
    textbookActivity:"Compare Fig. 6.15 and Fig. 6.16 from the chapter.",
    sources:["NCERT Class 9 Science, Chapter 6, Example 6.3, p. 101"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"second-law-idea", title:"Newton's Second Law: force, mass and acceleration", section:"6.5 Newton’s Second Law of Motion", pages:"102–104",
    hook:"The net force controls acceleration: more force gives more acceleration, more mass gives less acceleration for the same force.",
    textbook:"The chapter develops two relationships experimentally: for fixed mass, acceleration increases with net force; for fixed force, acceleration decreases as mass increases.",
    teacher:"The three quantities lock together. For a fixed object, doubling net force doubles acceleration in the ideal proportional relation; for fixed force, doubling mass halves acceleration.",
    example:"If the same mass experiences 10 N and then 20 N net force, the second case has twice the acceleration.",
    interaction:{type:"choice",prompt:"For a fixed mass, if net force is increased, acceleration:",options:["Increases","Must decrease","Must become zero","Stays exactly the same"],answer:0,explain:"The chapter states acceleration increases with net force for fixed mass."},
    mistake:"Do not say acceleration is proportional to force and mass at the same time. The chapter says direct with force and inverse with mass.",
    checkpoint:{prompt:"How does acceleration depend on net force and mass?","answer":"Directly on net force and inversely on mass."},
    textbookActivity:"Predict the outcomes of Activities 6.3 and 6.4 before checking the chapter's conclusion.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.5, pp. 102–104"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"activity-force-accel", title:"Activity 6.3: force vs acceleration", section:"6.5 Newton’s Second Law of Motion", pages:"102–103",
    hook:"The cart-and-pulley experiment tests whether a stronger pulling force gives a larger acceleration.",
    textbook:"The same cart travels the same distance from rest, while the mass hanging from the pulley is doubled to increase the pulling force. The measured times are compared using s = 1/2 aT².",
    teacher:"Because distance and initial velocity are the same, the time measurement lets you compare acceleration between the two force cases.",
    example:"The chapter derives a1 T1² = a2 T2² for the two trials, then concludes that increasing force for the same mass increases acceleration.",
    interaction:{type:"choice",prompt:"In Activity 6.3, which quantity is deliberately increased to increase the pulling force?",options:["Mass in the hanging cup","Time interval","Distance of the table","Wheel diameter"],answer:0,explain:"The cup mass is doubled in the second trial."},
    mistake:"The conclusion is about the same cart mass under different force conditions; do not mix this with the next experiment, where mass changes.",
    checkpoint:{prompt:"What relationship does Activity 6.3 support?","answer":"For fixed mass, greater net force produces greater acceleration."},
    textbookActivity:"Use the activity procedure as a classroom demonstration and record T1 and T2.",
    sources:["NCERT Class 9 Science, Chapter 6, Activity 6.3, pp. 102–103"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"activity-mass-accel", title:"Activity 6.4: mass vs acceleration", section:"6.5 Newton’s Second Law of Motion", pages:"103",
    hook:"The same force does not produce the same acceleration for every mass.",
    textbook:"Activity 6.4 keeps the hanging-cup force condition constant and doubles the mass of the cart. The acceleration is observed to decrease.",
    teacher:"If force is fixed, a heavier object accelerates less. This is why F=ma contains mass in the denominator when solving for acceleration.",
    example:"For the same net force, doubling the mass should reduce the acceleration by a factor of two in the ideal relation.",
    interaction:{type:"choice",prompt:"For the same force, increasing an object's mass makes its acceleration:",options:["Smaller","Larger","Unchanged in all cases","Undefined"],answer:0,explain:"The activity says acceleration is inversely related to mass for a given force."},
    mistake:"Do not conclude that a heavier object always feels a larger acceleration. The chapter's relationship is inverse for a given force.",
    checkpoint:{prompt:"What relationship does Activity 6.4 support?","answer":"For a given force, acceleration is inversely related to mass."},
    textbookActivity:"Repeat the cart experiment conceptually with a doubled cart mass.",
    sources:["NCERT Class 9 Science, Chapter 6, Activity 6.4, p. 103"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"fma", title:"The core equation: F = ma", section:"6.5 Newton’s Second Law of Motion", pages:"104",
    hook:"The two experimental relationships combine into one equation.",
    textbook:"The chapter writes a = F/m and equivalently F = ma, with acceleration in the direction of the net force.",
    teacher:"Use F=ma when the problem gives net force and mass or wants one of them. Remember this F is the net force in the chapter's law.",
    example:"For m = 5 kg and a = 2 m/s², F = 5×2 = 10 N.",
    interaction:{type:"numeric",prompt:"A 4 kg object has a net acceleration of 3 m/s². What net force acts on it?",answer:"12 N",explain:"F = ma = 4 × 3 = 12 N."},
    mistake:"Do not use just one applied force in place of net force when other forces matter.",
    checkpoint:{prompt:"Write Newton's second-law equation for constant mass.","answer":"F = ma."},
    textbookActivity:"Solve the chapter's Example 6.5 using F = ma after finding the net force.",
    sources:["NCERT Class 9 Science, Chapter 6, Eq. 6.1–6.2, p. 104"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"newton-unit", title:"Why 1 N = 1 kg m/s²", section:"6.5 Newton’s Second Law of Motion", pages:"104",
    hook:"The unit newton comes directly from F = ma.",
    textbook:"For m = 1 kg and a = 1 m/s², F = 1 kg m/s² = 1 N. One newton is the force that produces 1 m/s² acceleration in a 1 kg mass.",
    teacher:"This is a definition, not a conversion trick. It also explains why force units contain mass and acceleration units.",
    example:"A force of 8 N on 2 kg gives a = 8/2 = 4 m/s².",
    interaction:{type:"choice",prompt:"Which is equivalent to 1 N?",options:["1 kg m/s²","1 kg/s","1 m/s²","1 kg m²/s"],answer:0,explain:"From F = ma, 1 N = 1 kg × 1 m/s²."},
    mistake:"Do not write N as kg/s²; the metre factor is essential.",
    checkpoint:{prompt:"Give the SI base-form expression for one newton.","answer":"1 kg m/s²."},
    textbookActivity:"Convert a few F=ma calculations into newtons and show the units.",
    sources:["NCERT Class 9 Science, Chapter 6, Eq. 6.2 and definition of 1 N, p. 104"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"gravity-force", title:"Weight: F = mg", section:"6.5 Newton’s Second Law of Motion", pages:"104",
    hook:"Weight is the gravitational force exerted by Earth.",
    textbook:"Using F = ma with the acceleration due to gravity g, the chapter gives gravitational force F = mg.",
    teacher:"When the force is specifically Earth's gravitational force, use g for the acceleration and call the force weight.",
    example:"For a 2 kg object near Earth's surface, weight = 2×9.8 = 19.6 N downward.",
    interaction:{type:"numeric",prompt:"What is the gravitational force on a 5 kg object using g = 9.8 m/s²?",answer:"49 N",explain:"F = mg = 5 × 9.8 = 49 N."},
    mistake:"Do not confuse mass in kg with weight in N.",
    checkpoint:{prompt:"What equation does the chapter give for gravitational force?","answer":"F = mg."},
    textbookActivity:"Use Example 6.4 as the model for finding the force required to hold a barbell steady.",
    sources:["NCERT Class 9 Science, Chapter 6, Eq. 6.3, p. 104"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"g-value", title:"The value of g", section:"6.5 Newton’s Second Law of Motion", pages:"104",
    hook:"Near Earth's surface, the chapter takes gravitational acceleration as about 9.8 m/s².",
    textbook:"The chapter gives g = 9.8 m/s² and says it can be taken nearly constant near Earth's surface; for quick estimates, g = 10 m/s² may be used.",
    teacher:"Use 9.8 when the question expects the chapter's precise value and 10 when an estimate is explicitly appropriate.",
    example:"At g=9.8 m/s², a 30 kg barbell weighs 294 N.",
    interaction:{type:"choice",prompt:"Which value is the chapter's stated standard value near Earth's surface?",options:["9.8 m/s²","98 m/s²","0.98 m/s²","9.8 m/s"],answer:0,explain:"The chapter states g = 9.8 m/s² and permits 10 m/s² for quick estimates."},
    mistake:"The unit is m/s², not m/s.",
    checkpoint:{prompt:"What value of g does the chapter use near Earth's surface?","answer":"9.8 m/s²; 10 m/s² may be used for quick estimates."},
    textbookActivity:"Compare exact and quick-estimate weight calculations using both g values.",
    sources:["NCERT Class 9 Science, Chapter 6, p. 104"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"g-independence", title:"Gravitational acceleration and mass", section:"6.5 Newton’s Second Law of Motion", pages:"104",
    hook:"The chapter emphasises that g does not depend on the mass of the falling object.",
    textbook:"A note in the chapter states that the acceleration due to Earth's gravitational force does not depend on the mass of the object.",
    teacher:"Two objects can have different weights while the gravitational acceleration near Earth's surface is taken the same in the chapter.",
    example:"A 1 kg object and a 10 kg object have different weights, but the same g value is used for both near Earth's surface.",
    interaction:{type:"choice",prompt:"According to the chapter, does g depend on the object's mass?",options:["No","Yes, directly","Yes, inversely","Only for heavy objects"],answer:0,explain:"The chapter explicitly states that g does not depend on the mass of the object."},
    mistake:"Different weight does not imply different gravitational acceleration in this chapter's near-Earth treatment.",
    checkpoint:{prompt:"Does g depend on the object's mass?","answer":"No, not in the chapter's near-Earth model."},
    textbookActivity:"Explain why two objects of different masses still use the same g in weight calculations.",
    sources:["NCERT Class 9 Science, Chapter 6, note after Eq. 6.3, p. 104"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"catching-airbag", title:"Increasing stopping time reduces force", section:"6.5 Newton’s Second Law of Motion", pages:"104–105",
    hook:"The way you stop a moving object can change the force dramatically.",
    textbook:"The chapter explains that a fielder pulls hands backward while catching a fast ball, increasing the time over which the ball slows to zero, reducing acceleration magnitude and therefore required force.",
    teacher:"The same change in velocity spread over more time means a smaller magnitude of acceleration, so F=ma gives a smaller force for the same mass.",
    example:"Airbags similarly increase the time over which a passenger's head/chest is brought to rest during a collision.",
    interaction:{type:"choice",prompt:"Why does increasing stopping time reduce the force for the same mass and velocity change?",options:["It reduces the magnitude of acceleration","It increases mass","It removes all forces","It makes velocity larger"],answer:0,explain:"Acceleration is change in velocity divided by time; a longer time gives a smaller magnitude for the same change."},
    mistake:"Do not say the airbag makes the momentum change disappear. The chapter's point is that the change happens over a longer time.",
    checkpoint:{prompt:"What is the key idea behind the airbag example?","answer":"Increase stopping time → reduce acceleration magnitude → reduce force."},
    textbookActivity:"Explain both the fielder and airbag examples using F=ma.",
    sources:["NCERT Class 9 Science, Chapter 6, pp. 104–105"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"coconut-example", title:"Large stopping force: the coconut example", section:"6.5 Newton’s Second Law of Motion", pages:"105",
    hook:"Stopping a moving object in a very short time can require a large force.",
    textbook:"The chapter explains that a coconut brought down at high velocity and stopped in a very short time experiences a large force from the ground.",
    teacher:"This is the same stopping-time idea as the fielder example, but in reverse: very short stopping time means large acceleration magnitude.",
    example:"A coconut hits a hard surface and stops quickly, so the required force is large enough to break the shell.",
    interaction:{type:"choice",prompt:"A very short stopping time tends to make the magnitude of acceleration:",options:["Larger","Smaller","Exactly zero","Independent of velocity change"],answer:0,explain:"A large velocity change over a very short time gives a large acceleration magnitude."},
    mistake:"Do not assume a hard object automatically creates a large force. The force depends on how rapidly the velocity changes.",
    checkpoint:{prompt:"Why is the stopping force large in the coconut example?","answer":"The coconut's velocity changes sharply in a very short time."},
    textbookActivity:"Compare the coconut and airbag examples in one table.",
    sources:["NCERT Class 9 Science, Chapter 6, p. 105"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"barbell-example", title:"Example 6.4: holding a barbell steady", section:"6.5 Newton’s Second Law of Motion", pages:"105",
    hook:"Balanced forces can include a large weight and an equal upward force.",
    textbook:"The barbell has 30 kg total mass, so its gravitational force is 294 N downward. To keep it steady, the weightlifter applies 294 N upward.",
    teacher:"Steady means acceleration zero. Therefore the net force is zero, so the upward force must balance the 294 N weight.",
    example:"m = 30 kg, g = 9.8 m/s² → weight = 294 N downward; applied force = 294 N upward.",
    interaction:{type:"numeric",prompt:"A 30 kg barbell is held steady using g = 9.8 m/s². What upward force is required?",answer:"294 N upward",explain:"Weight = mg = 30×9.8 = 294 N downward, so an equal upward force keeps net force zero."},
    mistake:"Do not use F=ma with a non-zero acceleration here. Steady means a = 0.",
    checkpoint:{prompt:"Why is the upward force equal to the barbell's weight?","answer":"Because the barbell is steady, so the net force is zero."},
    textbookActivity:"Draw the two main vertical forces for the barbell and label their magnitudes.",
    sources:["NCERT Class 9 Science, Chapter 6, Example 6.4, p. 105"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"friction-block-example", title:"Example 6.5: pushing against friction", section:"6.5 Newton’s Second Law of Motion", pages:"105",
    hook:"Before using F=ma, calculate the net force actually acting on the block.",
    textbook:"A 25 kg block faces a maximum friction force of 50 N. A 50 N push gives zero net force and zero displacement; a 55 N push leaves 5 N net force, giving a=0.2 m/s² and displacement 0.4 m in 2 s.",
    teacher:"The workflow is net force first, acceleration second, kinematics third.",
    example:"For 55 N push: F_net = 55−50 = 5 N; a = 5/25 = 0.2 m/s²; from rest, s=1/2at²=0.4 m.",
    interaction:{type:"numeric",prompt:"A 25 kg block has 50 N friction and is pushed with 55 N. Find its acceleration.",answer:"0.2 m/s²",explain:"Net force = 55−50 = 5 N, so a=F/m=5/25=0.2 m/s²."},
    mistake:"Do not use 55 N directly in F=ma. The friction must be subtracted first.",
    checkpoint:{prompt:"What three-step method does Example 6.5 illustrate?","answer":"Find net force → use F=ma → use kinematics if displacement is needed."},
    textbookActivity:"Solve both parts of Example 6.5 and compare the balanced/unbalanced cases.",
    sources:["NCERT Class 9 Science, Chapter 6, Example 6.5, p. 105"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"vt-force", title:"Force from a velocity-time graph", section:"6.5 Newton’s Second Law of Motion", pages:"106",
    hook:"A velocity-time graph can give acceleration, and acceleration gives force.",
    textbook:"Example 6.6 uses the slope of a v-t graph to find acceleration, then F=ma to find the force on a 1500 kg sports car.",
    teacher:"Read the graph interval first. Find acceleration from rise over run, then multiply by mass.",
    example:"0–5 s: slope = (10−0)/5 = 2 m/s², so F=1500×2=3000 N east. 5–10 s: slope 0, so force 0. 10–15 s: slope -2 m/s², so force -3000 N west.",
    interaction:{type:"numeric",prompt:"A 1000 kg car changes velocity from 0 to 8 m/s in 4 s. Using the v-t slope, find the net force.",answer:"2000 N",explain:"a=(8−0)/4=2 m/s², so F=ma=1000×2=2000 N."},
    mistake:"Do not read the velocity value itself as acceleration. Acceleration is the slope of the v-t graph.",
    checkpoint:{prompt:"How do you get force from a v-t graph?","answer":"Find the slope for acceleration, then multiply by mass."},
    textbookActivity:"Reproduce the three time intervals from Fig. 6.21 and calculate the force in each.",
    sources:["NCERT Class 9 Science, Chapter 6, Example 6.6, p. 106"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"third-law", title:"Newton's Third Law", section:"6.6 Newton’s Third Law of Motion", pages:"107–108",
    hook:"Forces arise in interactions: when one object pushes, the other pushes back.",
    textbook:"Whenever one object exerts a force on a second object, the second object simultaneously exerts an equal and opposite force on the first object.",
    teacher:"The key phrase is 'two different objects'. That single detail prevents the most common third-law mistake.",
    example:"When your foot pushes a ball, the ball exerts a force on your foot in the opposite direction.",
    interaction:{type:"choice",prompt:"Newton's third-law force pair acts on:",options:["Two different objects","The same object","Only the larger-mass object","Only the moving object"],answer:0,explain:"The chapter explicitly states the paired forces act on two different objects."},
    mistake:"Equal and opposite third-law forces do not cancel because they act on different objects.",
    checkpoint:{prompt:"State Newton's third law in your own words.","answer":"For every force one object exerts on another, the other exerts an equal opposite force back."},
    textbookActivity:"Use Activity 6.5 to observe the chair moving opposite when the table is pushed.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.6, pp. 107–108"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"third-law-friction", title:"Friction can help us move", section:"6.6 Newton’s Third Law of Motion", pages:"107–108",
    hook:"The friction that often slows a box can also push you forward when you walk.",
    textbook:"While walking, the foot pushes the ground backward. The ground exerts friction on the foot in the forward direction, helping the person move.",
    teacher:"Always identify which object the friction acts on and what relative motion is being prevented. Here friction from the ground helps the foot move forward.",
    example:"Soles and tyre treads provide grip so the foot or tyre can push backward without slipping.",
    interaction:{type:"choice",prompt:"During normal walking, the ground's frictional force on the foot is directed:",options:["Forward","Backward","Upward only","Downward only"],answer:0,explain:"The chapter says the ground applies friction in the forward direction on the person."},
    mistake:"Never memorise 'friction always opposes motion' without identifying the contact interaction.",
    checkpoint:{prompt:"Why is friction useful for walking?","answer":"It provides a forward force when the foot pushes the ground backward."},
    textbookActivity:"Explain the role of shoe grooves and tyre treads using the chapter's friction discussion.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.6, p. 107"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"canoe", title:"Canoe motion and Newton's Third Law", section:"6.6 Newton’s Third Law of Motion", pages:"108",
    hook:"Push water backward and the water pushes the paddle—and canoe—forward.",
    textbook:"The canoeist pushes water backward with the paddle. The water exerts an equal and opposite force on the paddle and canoe, producing forward motion.",
    teacher:"The third-law pair is paddle on water and water on paddle. They act on different objects, so they do not cancel on the canoe.",
    example:"Paddling harder increases the forward force on the paddle and canoe, increasing velocity; the chapter also notes drag, currents and mass matter.",
    interaction:{type:"choice",prompt:"Why does a canoe move forward when the paddle pushes water backward?",options:["Water exerts an opposite force forward","The paddle creates force from nothing","Gravity pulls the canoe forward","The water has no reaction"],answer:0,explain:"The chapter directly uses Newton's third law for rowing."},
    mistake:"Do not pair the forward force on the canoe with the backward paddle-on-water force as though they act on the same object.",
    checkpoint:{prompt:"What is the action-reaction pair in rowing?","answer":"Paddle pushes water backward; water pushes paddle/canoe forward."},
    textbookActivity:"Identify action-reaction pairs in three other examples from the chapter.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.6, p. 108"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"rocket", title:"Rocket propulsion", section:"6.6 Newton’s Third Law of Motion", pages:"109",
    hook:"A rocket accelerates upward because exhaust is expelled downward.",
    textbook:"The engine expels gas downward. The gas exerts an equal and opposite force on the rocket upward; when this exceeds the rocket's weight, the net force is upward.",
    teacher:"There are two layers: third-law interaction creates the upward force pair, then the net force determines the rocket's acceleration.",
    example:"The chapter also explains that firing a spacecraft engine opposite its motion can slow it down; the text cites the Vikram lander as an application.",
    interaction:{type:"choice",prompt:"For the launch described in the chapter, exhaust gas is expelled:",options:["Downward","Upward","Sideways only","Nowhere"],answer:0,explain:"The rocket expels exhaust downward and receives an equal opposite force upward."},
    mistake:"Do not say the exhaust force is the same as the net force. Weight also acts on the rocket.",
    checkpoint:{prompt:"What makes the rocket lift off?","answer":"The upward reaction force exceeds the downward weight, giving an upward net force."},
    textbookActivity:"Use Activity 6.7 as the balloon analogue for rocket propulsion.",
    sources:["NCERT Class 9 Science, Chapter 6, Activity 6.7 and rocket discussion, p. 109"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"third-law-noncontact", title:"Third law for non-contact forces", section:"6.6 Newton’s Third Law of Motion", pages:"110",
    hook:"Newton's third law is not limited to touch-based interactions.",
    textbook:"The chapter applies the third law to magnetic, electrostatic and gravitational interactions and notes that the forces are equal and opposite on the interacting objects.",
    teacher:"The objects can push/pull through a field. The third-law pair still acts on different objects.",
    example:"A bar magnet and a compass needle exert equal and opposite magnetic forces on each other.",
    interaction:{type:"choice",prompt:"Which is an example of a non-contact third-law pair discussed in the chapter?",options:["Magnet and compass","Hand and table only","Shoes and floor only","Ball and bat only"],answer:0,explain:"The chapter explicitly shows magnetic and electrostatic examples."},
    mistake:"Third-law forces do not require physical contact.",
    checkpoint:{prompt:"Name one non-contact interaction used to illustrate the third law.","answer":"Magnetic, electrostatic or gravitational interaction."},
    textbookActivity:"Compare the magnet-compass example with the Earth-fruit example.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.6, p. 110"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"earth-fruit", title:"Equal forces do not mean equal acceleration", section:"6.6 Newton’s Third Law of Motion", pages:"110",
    hook:"Equal action-reaction forces can produce very different accelerations when masses differ.",
    textbook:"For the Earth and fruit, the gravitational forces are equal and opposite, but the Earth's huge mass makes its acceleration extremely small compared with the fruit's.",
    teacher:"Use the pair F and −F, then apply a=F/m to each object. Same force magnitude does not imply same acceleration when masses differ.",
    example:"The chapter explains why the fruit noticeably moves toward Earth while Earth's motion toward the fruit is too small to notice.",
    interaction:{type:"choice",prompt:"Why is the Earth's acceleration in the Earth-fruit pair so small?",options:["Earth has enormous mass","Earth has no force on it","The forces are unequal","Gravity acts only on fruit"],answer:0,explain:"With the same force magnitude, a = F/m is tiny for Earth's huge mass."},
    mistake:"Do not claim the third-law forces differ. The chapter says they are equal in magnitude and opposite.",
    checkpoint:{prompt:"Why can equal forces produce unequal accelerations?","answer":"Because the masses of the two objects can be different."},
    textbookActivity:"Use a=F/m to compare the qualitative accelerations of Earth and a fruit.",
    sources:["NCERT Class 9 Science, Chapter 6, Example 6.7, p. 110"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"bullet-gun", title:"Example 6.8: bullet and gun recoil", section:"6.6 Newton’s Third Law of Motion", pages:"110",
    hook:"Equal recoil forces can produce very different accelerations.",
    textbook:"A 0.1 kg bullet and a 5 kg gun experience equal 2 N interaction-force magnitudes. Their initial accelerations are 20 m/s² for the bullet and 0.4 m/s² for the gun.",
    teacher:"Third law gives the equal force pair. Second law then tells you each object's acceleration from its own mass.",
    example:"Gun: a=2/5=0.4 m/s². Bullet: a=2/0.1=20 m/s².",
    interaction:{type:"numeric",prompt:"A 5 kg gun experiences a 2 N recoil force. What is its initial acceleration magnitude?",answer:"0.4 m/s²",explain:"a=F/m=2/5=0.4 m/s²."},
    mistake:"Do not divide the force by the combined mass. Each object's acceleration uses its own mass.",
    checkpoint:{prompt:"What explains the different accelerations in Example 6.8?","answer":"The forces are equal but the masses are different."},
    textbookActivity:"Calculate both accelerations from the example and compare their ratio.",
    sources:["NCERT Class 9 Science, Chapter 6, Example 6.8, p. 110"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"system-intro", title:"Why treat objects as a system?", section:"6.7 Forces Acting on a System of Objects", pages:"111",
    hook:"Several connected objects can sometimes be easier to analyse as one system.",
    textbook:"For two connected boxes, internal tension forces act within the system while the external pulling force F acts on the whole system.",
    teacher:"Choose the system boundary first. Internal forces can cancel within the system, leaving only external forces for system acceleration.",
    example:"Two boxes of masses m1 and m2 on a frictionless surface connected by a string are pulled by an external F.",
    interaction:{type:"choice",prompt:"When the two boxes and string are treated as one system, tension is considered:",options:["Internal to the system","The only external force","Zero force","An unrelated force"],answer:0,explain:"The chapter says tension is internal while F is external."},
    mistake:"Whether a force is internal or external depends on the system boundary you choose.",
    checkpoint:{prompt:"What is the advantage of treating connected objects as a system?","answer":"Internal forces need not be considered; only external forces determine system acceleration."},
    textbookActivity:"Draw the two-box system and circle the forces that are external to the system.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.7, p. 111"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"system-acceleration", title:"Acceleration of a two-box system", section:"6.7 Forces Acting on a System of Objects", pages:"111",
    hook:"For a frictionless two-box system, the whole mass accelerates under the external force.",
    textbook:"The chapter gives a = F/(m1+m2) for two connected boxes on a frictionless horizontal surface when F is the external pulling force.",
    teacher:"Add the masses first because the whole system shares the same acceleration.",
    example:"If F=20 N, m1=2 kg and m2=3 kg, then a=20/(2+3)=4 m/s².",
    interaction:{type:"numeric",prompt:"Two connected boxes have masses 2 kg and 3 kg. An external force of 20 N pulls the system on a frictionless surface. Find acceleration.",answer:"4 m/s²",explain:"a = F/(m1+m2) = 20/(2+3) = 4 m/s²."},
    mistake:"Do not use only one box's mass when calculating the acceleration of the full system.",
    checkpoint:{prompt:"Write the system-acceleration formula for the two-box example.","answer":"a = F/(m1 + m2)."},
    textbookActivity:"Substitute different masses into Eq. 6.4 and observe how the acceleration changes.",
    sources:["NCERT Class 9 Science, Chapter 6, Eq. 6.4, p. 111"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"system-external", title:"Internal vs external forces", section:"6.7 Forces Acting on a System of Objects", pages:"111",
    hook:"The right system boundary can make a complicated force problem simple.",
    textbook:"For the two-box system, tension is internal. The pulling force F is external. The system also has total weight downward and total normal force upward, which balance on the horizontal surface.",
    teacher:"A force can be internal in one choice of system and external in another. State your system before simplifying.",
    example:"For the two boxes plus string, total weight (m1+m2)g is downward and N1+N2 upward.",
    interaction:{type:"choice",prompt:"Which force is external in the chapter's two-box system?",options:["The pulling force F","The tension between the boxes","Both tensions inside the string","None"],answer:0,explain:"The chapter identifies F as the external force and tension as internal."},
    mistake:"Do not throw away weight and normal force blindly; they balance here because of the horizontal-surface setup.",
    checkpoint:{prompt:"What makes tension internal in this setup?","answer":"It acts between parts that are both inside the chosen system."},
    textbookActivity:"Redraw Fig. 6.35 and label the external vertical forces.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.7, p. 111"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"momentum-extension", title:"Momentum: a higher-level extension", section:"6.5 Newton’s Second Law of Motion", pages:"104",
    hook:"The chapter briefly points to the more complete form of Newton's second law.",
    textbook:"The 'Ready to Go Beyond' section defines momentum as mass times velocity and says the rate of change of momentum is proportional to net force; it notes this form handles variable mass situations.",
    teacher:"Treat this as an extension, not as an extra Grade 9 derivation for this chapter. The supplied text introduces the idea but does not develop a full momentum problem set.",
    example:"Momentum has magnitude related to mass and velocity and its direction is the same as velocity.",
    interaction:{type:"choice",prompt:"How does the chapter define momentum?",options:["Product of mass and velocity","Mass divided by velocity","Force times distance","Acceleration divided by time"],answer:0,explain:"The text defines momentum as mass multiplied by velocity."},
    mistake:"Do not present the extension as if the supplied chapter develops full variable-mass momentum calculations.",
    checkpoint:{prompt:"What is momentum in the chapter's extension section?","answer":"Mass × velocity."},
    textbookActivity:"Read the extension and note why the chapter says it is useful when mass is not constant.",
    sources:["NCERT Class 9 Science, Chapter 6, Ready to Go Beyond, p. 104"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"graph-force-overview", title:"Force, acceleration and graph thinking", section:"6.5–6.7 Applications and graphs", pages:"103–114",
    hook:"Chapter 6 turns graphs into force calculations by linking slope to acceleration and acceleration to force.",
    textbook:"The chapter uses velocity-time graphs for the sports car and an acceleration-mass graph in the revision set, and asks students to interpret force through F=ma.",
    teacher:"When you see a graph, first identify the axes. Then decide whether the slope gives acceleration or whether the values must be combined with mass to find force.",
    example:"A v-t slope of 2 m/s² for a 1500 kg car corresponds to 3000 N.",
    interaction:{type:"choice",prompt:"For a velocity-time graph, what does the slope give?",options:["Acceleration","Force directly","Mass directly","Distance directly"],answer:0,explain:"Slope of v-t is acceleration; the chapter then uses F=ma to obtain force."},
    mistake:"Do not call the area under a v-t graph 'force'. In this chapter, slope gives acceleration and then F=ma gives force.",
    checkpoint:{prompt:"What is the graph-to-force pipeline?","answer":"v-t slope → acceleration → multiply by mass → force."},
    textbookActivity:"Revisit Example 6.6 and the force-related revision graph questions.",
    sources:["NCERT Class 9 Science, Chapter 6, Example 6.6 and Revise, Reflect, Refine, pp. 106, 113–114"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"numerical-strategy", title:"A reliable Chapter 6 numerical strategy", section:"6.2–6.7 Mixed Applications", pages:"96–114",
    hook:"Most force numericals become manageable when solved in the right order.",
    textbook:"The chapter repeatedly combines force diagrams, net force, F=ma, kinematics and graph slopes in its worked examples and revision questions.",
    teacher:"Use this order: identify the system, list forces, find net force, choose F=ma, convert units if needed, then use kinematics or graph data.",
    example:"Block with push and friction: F_net → a → s. Sports car: v-t slope → a → F.",
    interaction:{type:"choice",prompt:"For a block pushed against friction, what should you usually calculate first?",options:["Net force","Displacement","Weight in joules","Graph area"],answer:0,explain:"You need the net force before using F=ma."},
    mistake:"Starting with a memorised formula without checking the force diagram is a common source of errors.",
    checkpoint:{prompt:"Name the basic order for a mixed force numerical.","answer":"System/forces → net force → F=ma → kinematics or graph step → units/check."},
    textbookActivity:"Use Examples 6.5 and 6.6 to practise the workflow.",
    sources:["NCERT Class 9 Science, Chapter 6, Examples 6.5–6.6, pp. 105–106"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"review-laws", title:"Three laws: one framework", section:"6.4–6.6 Newton’s Laws of Motion", pages:"100–110",
    hook:"Newton's three laws answer three different questions about force and motion.",
    textbook:"First law covers motion when net force is zero; second law relates net force, mass and acceleration; third law describes paired forces between interacting objects.",
    teacher:"Think: Law 1 = what if net force is zero? Law 2 = what if there is a net force? Law 3 = how do interacting objects force each other?",
    example:"A constant-velocity car illustrates first law; F=ma illustrates second; walking or rowing illustrates third.",
    interaction:{type:"choice",prompt:"Which law directly gives F=ma in the chapter?",options:["Second law","First law","Third law","None"],answer:0,explain:"The second law is expressed mathematically as a=F/m or F=ma."},
    mistake:"Do not mix the third-law pair with the net-force sum acting on one object.",
    checkpoint:{prompt:"Give one phrase for each Newton law.","answer":"1: zero net force → unchanged velocity; 2: F=ma; 3: equal-opposite interaction pair on different objects."},
    textbookActivity:"Make a three-column table of the law, equation/statement and one chapter example.",
    sources:["NCERT Class 9 Science, Chapter 6, 6.4–6.6, pp. 100–110"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  },
  {
    key:"chapter-mastery", title:"Chapter 6 mastery", section:"6.1–6.7", pages:"94–115",
    hook:"Mastery means you can connect force, net force, laws, friction, graphs and systems in one problem.",
    textbook:"The chapter ends by revisiting friction, the three laws, system thinking and further investigation.",
    teacher:"A strong Chapter 6 student should be able to explain concepts, draw force directions, calculate net force, solve F=ma problems, read graphs and identify action-reaction pairs.",
    example:"A mixed problem may require force balance, friction, F=ma and then a kinematic equation.",
    interaction:{type:"choice",prompt:"What is the strongest sign of Chapter 6 mastery?",options:["You can explain why each step is valid","You only memorised F=ma","You can list law names without applying them","You can copy one worked example"],answer:0,explain:"The chapter is application-heavy: understanding the chain of ideas matters more than isolated memorisation."},
    mistake:"Do not treat formulas as isolated facts. Link each equation to the physical situation and units.",
    checkpoint:{prompt:"What is the full Chapter 6 loop?","answer":"Identify forces → net force → choose the relevant Newton law → calculate/interpret motion → check directions and units."},
    textbookActivity:"Use the chapter's Revise, Reflect, Refine questions as the final self-test.",
    sources:["NCERT Class 9 Science, Chapter 6, At a Glance and Revise, Reflect, Refine, pp. 112–114"],
    externalReferences:[{label:"Official NCERT Chapter 6",url:"https://ncert.nic.in/textbook/pdf/iesc106.pdf"}]
  }
];
export default chapter6Lessons;