const chapter6Flashcards = [
["What three changes can a force produce on an object's motion?","It can change an object's state of rest, its speed, or its direction of motion."],
["Besides changing motion, what physical effect can a force have on an object?","It can change the shape of the object."],
["Squeezing a lemon with fingers is an example of a force causing what type of change?","A change in the shape of an object."],
["Why does a canoe move forward when a canoeist pushes water backwards with a paddle?","The backward force on the water generates an equal forward reaction force on the canoe."],
["How does increasing the backward paddling force affect a canoe's motion?","It increases the canoe's forward acceleration, causing it to move faster."],
["If the same force is applied to an empty canoe and a loaded canoe, which accelerates faster?","The empty canoe, because it has less mass."],
["Why is force classified as a vector quantity?","Because specifying a force requires both its magnitude and its direction."],
["What is the SI unit of force?","The newton ($\\text{N}$)."],
["How is the unit name 'newton' written when spelled out in full text?","With a lowercase initial letter ('newton')."],
["What property of a force expresses its strength?","Its magnitude."],
["What happens to the overall effect of a force on an object if either its magnitude or direction changes?","The effect of the force changes."],
["What measuring device is used to measure the magnitude of a force in general?","A spring balance."],
["The weight of an object is defined as the gravitational force exerted on it by _____.","the Earth"],
["What is the order of magnitude of the smallest forces directly feelable by human touch?","Millinewtons ($10^{-3}\\text{ N}$)."],
["What is the smallest magnitude of force measurable in specialized experiments as of 2026?","Yoctonewtons ($10^{-24}\\text{ N}$)."],
["Two forces acting on an object in opposite directions with equal magnitude are called _____ forces.","balanced"],
["What is the net force acting on an object when balanced forces are applied?","Zero ($0\\text{ N}$)."],
["When two opposite forces of unequal magnitude act on a body, how is the net force magnitude calculated?","By subtracting the smaller force magnitude from the larger force magnitude."],
["What determines the direction of the net force when two unequal opposite forces act on an object?","The direction of the force with the larger magnitude."],
["When two forces act on an object in the same direction, how is the net force magnitude calculated?","By adding the magnitudes of the two individual forces."],
["What is the direction of the net force when two individual forces act in the same direction?","The same direction as the two individual forces."],
["If a $10\\text{ N}$ force to the right and a $6\\text{ N}$ force to the right act on a block, what is the net force?","$16\\text{ N}$ towards the right side."],
["If a $10\\text{ N}$ force acts to the right and a $6\\text{ N}$ force acts to the left on a block, what is the net force?","$4\\text{ N}$ towards the right side."],
["If a $10\\text{ N}$ force acts to the left and a $6\\text{ N}$ force acts to the right on a block, what is the net force?","$4\\text{ N}$ towards the left side."],
["Equal and opposite forces applied to opposite ends of an extended object cause the object to _____.","rotate"],
["Turning a bicycle handlebar or a tap handle is an example of applying equal and opposite forces to produce _____.","rotation"],
["In what direction does the force of friction act relative to an object's motion?","In the direction opposite to the direction of motion."],
["Under what condition will a stationary box begin moving across a floor when pushed?","When the applied force magnitude exceeds the opposing force of friction."],
["What upward force is exerted by a surface on an object placed upon it?","The normal force."],
["In what direction does the normal force act relative to the contact surface?","Perpendicular to the surface in the upward direction."],
["The downward weight of a stationary box resting on a table is balanced by which upward force?","The normal force."],
["Why does a rolling ball on a floor eventually come to rest if left untouched?","The force of friction between the ball and floor slows it down to a stop."],
["What ancient misconception about continuous motion did Galileo Galilei disprove?","The belief that a continuous force was required to maintain an object in motion at constant velocity."],
["According to Galileo, what happens to a moving body on a horizontal plane if all friction is removed?","It will continue to move indefinitely with constant velocity."],
["Term: Inertia","Definition: The natural tendency of objects to resist any change in their state of rest or uniform motion."],
["Who introduced the word 'inertia' to describe an object's tendency to resist changes in motion?","Isaac Newton."],
["State Newton's First Law of Motion.","An object at rest remains at rest, and an object in motion continues to move with a constant velocity, unless a net force acts upon it."],
["What is the acceleration of an object if the net force acting on it is zero?","Zero ($0\\text{ m s}^{-2}$)."],
["A motion with constant velocity requires that both speed and _____ remain unchanged.","direction"],
["If friction is completely absent, how much force is required to keep an object moving at constant velocity?","No force is required."],
["How does doubling the net force applied to a fixed mass affect its acceleration?","It doubles the acceleration."],
["How does doubling the mass of an object affect its acceleration for a given net force?","It reduces the acceleration by half."],
["State Newton's Second Law of Motion in terms of net force, mass, and acceleration.","When a net force acts on an object, it accelerates in the direction of the force with a magnitude proportional to the net force and inversely proportional to its mass."],
["Formula: What equation expresses Newton's Second Law relating force ($F$), mass ($m$), and acceleration ($a$)?","$F = ma$"],
["In the equation $F = ma$, what is the relationship between the direction of force and direction of acceleration?","The direction of acceleration is identical to the direction of the net force."],
["Define one newton ($1$ N) of force using SI units.","The force that produces an acceleration of $1\\text{ m s}^{-2}$ on a mass of $1\\text{ kg}$ ($1$ N = $1$ kg m s$^{-2}$)."],
["What physical quantity is defined as the product of an object's mass and its velocity?","Momentum."],
["What is the direction of an object's momentum vector?","The same direction as its velocity vector."],
["State Newton's Second Law of Motion in terms of momentum.","The rate of change of momentum of an object is proportional to the net force and takes place in the direction of the net force."],
["Why is the momentum formulation of Newton's second law more general than $F = ma$?","Because it remains applicable to situations where the mass of the object is not constant."],
["Why does a cricket fielder pull their hands backward while catching a fast-moving ball?","To increase catching time, which decreases acceleration and reduces the impact force on the hands."],
["How does increasing the time duration over which a moving object stops affect the stopping force?","It reduces the magnitude of the force required to stop the object."],
["State Newton's Third Law of Motion.","Whenever one object exerts a force on a second object, the second object exerts an equal and opposite force on the first object."],
["Why do Newton's third law action-reaction force pairs fail to cancel each other out?","Because the two forces act on two different objects."],
["Under what condition do equal and opposite forces balance each other to produce zero net force?","When both equal and opposite forces act on the same object."],
["In a rocket launch, what reaction force pushes the rocket upward?","The upward force exerted on the rocket by the downward-expelled exhaust gases."],
["When a fruit falls, how does the force on the fruit by Earth compare to the force on Earth by the fruit?","They are equal in magnitude and opposite in direction."],
["Why is the acceleration of the Earth toward a falling fruit imperceptible?","Because the Earth's mass is extremely large relative to the magnitude of the force."],
["In a multi-body system analyzed as a single unit, how are internal forces treated?","Internal forces cancel out and do not affect the system's net acceleration."],
["When analyzing two connected boxes as a single system, which forces determine the system's acceleration?","Only the external forces acting on the system."],
["Under what extreme domain condition do Newton's laws of motion require modification?","Near extremely massive objects, at speeds close to the speed of light, or at atomic scales."],
["In a tug-of-war game, if neither team moves, what can be concluded about the forces exerted by both teams?","The forces are equal in magnitude and opposite in direction, forming balanced forces."],
["In a tug-of-war game, what condition causes the rope to accelerate toward one team?","An unbalanced force resulting from one team exerting a larger magnitude of force."],
["If two people exert parallel forces of $150$ N and $200$ N in the same direction on a car, what is the net force?","$350$ N in the direction of the push."],
["What two vertical forces act on a ball floating on water?","Downward gravitational force and upward buoyant force."],
["When a weightlifter holds a barbell stationary above their head, are the forces on the barbell balanced or unbalanced?","Balanced forces, because the barbell remains at rest with zero acceleration."],
["Formula: What is the algebraic expression for momentum ($p$) in terms of mass ($m$) and velocity ($v$)?","$p = mv$"],
["In Activity 6.1 with the stacked coins and rubber band, why does the coin stack slow down after launch?","Because the force of friction between the coins and the surface opposes their motion."],
["What impact does air friction usually have on heavy objects moving across a table at low speeds?","Its magnitude is so small that it can be neglected."],
["If an object has a mass of $4$ kg and accelerates at $3$ m s$^{-2}$, what net force acts on it?","$12$ N"],
["If a net force of $20$ N produces an acceleration of $5$ m s$^{-2}$ on an object, what is its mass?","$4$ kg"],
["What net force is required to keep a $10$ kg object moving at a constant velocity of $5$ m s$^{-1}$ on a frictionless surface?","$0$ N"],
["What is the SI unit of momentum?","Kilogram meter per second ($\\text{kg m s}^{-1}$)."],
["In the system of two boxes tied by a string, what type of force is the string tension ($T$)?","An internal force."],
["In what year did Isaac Newton publish his three fundamental laws of motion?","1687"],
["What is the historical title of the work in which Isaac Newton presented his laws of motion?","The Principia."],
["What happens to the net force when two equal forces act on an object in opposite directions?","The net force is zero."],
["How does the acceleration of an object change if the net force acting on it is tripled while mass remains constant?","The acceleration triples."],
["If the net force on an object is zero, what can be stated about its motion?","It remains at rest or continues moving in a straight line with constant speed."],
["When equal and opposite forces act on the same single body, what is their combined effect on motion?","They produce zero net force, causing no change in velocity."]
];
export default chapter6Flashcards;
